name: Scheduled tasks

on:
  schedule:
    - cron:  '13 12 * * *'
  workflow_dispatch:

jobs:
  call-workflow:
    uses: radiorabe/actions/.github/workflows/schedule-trivy.yaml@v0.34.1
    with:
      image-ref: 'ghcr.io/radiorabe/mediawiki:latest'
